apiVersion: v1
kind: Service
metadata:
  labels:
    service: payment
  name: payment
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: payment
  sessionAffinity: None
  type: ClusterIP
