apiVersion: v1
kind: Service
metadata:
  labels:
    service: shipping
  name: shipping
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: shipping
  sessionAffinity: None
  type: ClusterIP
