apiVersion: v1
kind: Service
metadata:
  labels:
    service: ratings
  name: ratings
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: ratings
  sessionAffinity: None
  type: ClusterIP
