apiVersion: v1
kind: Service
metadata:
  labels:
    service: catalogue
  name: catalogue
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: catalogue
  sessionAffinity: None
  type: ClusterIP
