apiVersion: v1
kind: Service
metadata:
  labels:
    service: user
  name: user
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: user
  sessionAffinity: None
  type: ClusterIP
