apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
  name: web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - env:
        - name: INSTANA_EUM_KEY
          value: UaaNHIt3SeCfkZzzq_IfOA
        - name: INSTANA_EUM_REPORTING_URL
          value: http://instana.ibmdemo.local:86/eum/
        - name: INSTANA_SERVICE_NAME
          value: web_nginx
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: gitlab-ee.coc-ibm.com:5050/robot-shop/web/master:latest
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
