apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: web
  sessionAffinity: None
  type: LoadBalancer
